/bin/bash: error importing function definition for `BASH_FUNC_module()'
/bin/bash: error importing function definition for `BASH_FUNC_switchml()'
/bin/bash: error importing function definition for `BASH_FUNC__moduleraw()'
/home/rkogeyam/PATENT_CITATION
n055
Thu Jul 30 16:30:22 EDT 2020
Running program on 4 CPU cores
[NbConvertApp] Searching ['/home/rkogeyam/PATENT_CITATION', '/home/rkogeyam/.jupyter', '/home/applications/anaconda3/4.2.0/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[NbConvertApp] Looking for jupyter_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /home/applications/anaconda3/4.2.0/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /home/rkogeyam/.jupyter
[NbConvertApp] Looking for jupyter_config in /home/rkogeyam/PATENT_CITATION
[NbConvertApp] Looking for jupyter_nbconvert_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /home/applications/anaconda3/4.2.0/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /home/rkogeyam/.jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /home/rkogeyam/PATENT_CITATION
[NbConvertApp] Converting notebook graph_tool-v2.ipynb to notebook
[NbConvertApp] Notebook name is 'graph_tool-v2'
[NbConvertApp] Applying preprocessor: ExecutePreprocessor
[NbConvertApp] Executing notebook with kernel: m-env
[NbConvertApp] Found kernel m-env in /home/rkogeyam/.local/share/jupyter/kernels
[NbConvertApp] Native kernel (python3) available from /home/applications/anaconda3/4.2.0/lib/python3.5/site-packages/ipykernel/resources
[NbConvertApp] Starting kernel: ['/home/rkogeyam/.conda/envs/m-env/bin/python', '-m', 'ipykernel_launcher', '-f', '/tmp/tmphs0rt7fm.json']
[NbConvertApp] Connecting to: tcp://127.0.0.1:54132
[NbConvertApp] connecting shell channel to tcp://127.0.0.1:55404
[NbConvertApp] Connecting to: tcp://127.0.0.1:55404
[NbConvertApp] connecting iopub channel to tcp://127.0.0.1:36193
[NbConvertApp] Connecting to: tcp://127.0.0.1:36193
[NbConvertApp] connecting stdin channel to tcp://127.0.0.1:35179
[NbConvertApp] Connecting to: tcp://127.0.0.1:35179
[NbConvertApp] connecting heartbeat channel to tcp://127.0.0.1:37039
Traceback (most recent call last):
  File "/home/applications/anaconda3/4.2.0/bin/jupyter-nbconvert", line 6, in <module>
    main()
  File "/home/applications/anaconda3/4.2.0/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/applications/anaconda3/4.2.0/lib/python3.5/site-packages/traitlets/config/application.py", line 653, in launch_instance
    app.start()
  File "/home/applications/anaconda3/4.2.0/lib/python3.5/site-packages/nbconvert/nbconvertapp.py", line 293, in start
    self.convert_notebooks()
  File "/home/applications/anaconda3/4.2.0/lib/python3.5/site-packages/nbconvert/nbconvertapp.py", line 457, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/applications/anaconda3/4.2.0/lib/python3.5/site-packages/nbconvert/nbconvertapp.py", line 428, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/applications/anaconda3/4.2.0/lib/python3.5/site-packages/nbconvert/nbconvertapp.py", line 357, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/applications/anaconda3/4.2.0/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 165, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/applications/anaconda3/4.2.0/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 183, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/applications/anaconda3/4.2.0/lib/python3.5/site-packages/nbconvert/exporters/notebook.py", line 26, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/applications/anaconda3/4.2.0/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 130, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/applications/anaconda3/4.2.0/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 302, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/applications/anaconda3/4.2.0/lib/python3.5/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb,resources)
  File "/home/applications/anaconda3/4.2.0/lib/python3.5/site-packages/nbconvert/preprocessors/execute.py", line 141, in preprocess
    cwd=path)
  File "/home/applications/anaconda3/4.2.0/lib/python3.5/site-packages/jupyter_client/manager.py", line 433, in start_new_kernel
    kc.wait_for_ready(timeout=startup_timeout)
  File "/home/applications/anaconda3/4.2.0/lib/python3.5/site-packages/jupyter_client/blocking/client.py", line 63, in wait_for_ready
    raise RuntimeError("Kernel didn't respond in %d seconds" % timeout)
RuntimeError: Kernel didn't respond in 60 seconds
Thu Jul 30 16:31:30 EDT 2020
